// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';

export function OpenWorkspace(arg1:string):Promise<workspace.Workspace>;

export function SelectWorkspaceFolder():Promise<string>;
