// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';

export function AddIssueLink(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.Issue>;

export function AddProjectMember(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.Project>;

export function CreateIssue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.Issue>;

export function GetIdentity(arg1:string):Promise<workspace.Identity>;

export function OpenWorkspace(arg1:string):Promise<workspace.Workspace>;

export function SelectWorkspaceFolder():Promise<string>;

export function SetIdentity(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetIssueAssignee(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function SetIssueParent(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function SetIssueTitle(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function TransitionIssueStatus(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function UpdateIssueBody(arg1:string,arg2:string,arg3:string):Promise<void>;
