// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIssueLink(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddIssueLink'](arg1, arg2, arg3, arg4);
}

export function AddProjectMember(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddProjectMember'](arg1, arg2, arg3, arg4);
}

export function AddProjectRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddProjectRepo'](arg1, arg2, arg3, arg4);
}

export function AddTimelineNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTimelineNote'](arg1, arg2, arg3);
}

export function ArchiveProject(arg1, arg2) {
  return window['go']['main']['App']['ArchiveProject'](arg1, arg2);
}

export function CloneProjectRepos(arg1, arg2) {
  return window['go']['main']['App']['CloneProjectRepos'](arg1, arg2);
}

export function CreateIssue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateIssue'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function GetIdentity(arg1) {
  return window['go']['main']['App']['GetIdentity'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitStageAll(arg1) {
  return window['go']['main']['App']['GitStageAll'](arg1);
}

export function GitStagePaths(arg1, arg2) {
  return window['go']['main']['App']['GitStagePaths'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReadDocument(arg1, arg2) {
  return window['go']['main']['App']['ReadDocument'](arg1, arg2);
}

export function RecentWorkspaces() {
  return window['go']['main']['App']['RecentWorkspaces']();
}

export function RecordRecentWorkspace(arg1) {
  return window['go']['main']['App']['RecordRecentWorkspace'](arg1);
}

export function RemoveProjectRepo(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveProjectRepo'](arg1, arg2, arg3);
}

export function SelectWorkspaceFolder(arg1) {
  return window['go']['main']['App']['SelectWorkspaceFolder'](arg1);
}

export function SetIdentity(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIdentity'](arg1, arg2, arg3);
}

export function SetIssueAssignee(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIssueAssignee'](arg1, arg2, arg3);
}

export function SetIssueParent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIssueParent'](arg1, arg2, arg3);
}

export function SetIssuePriority(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIssuePriority'](arg1, arg2, arg3);
}

export function SetIssueTitle(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIssueTitle'](arg1, arg2, arg3);
}

export function SetProjectIssueTypes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProjectIssueTypes'](arg1, arg2, arg3);
}

export function SetWorkflow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetWorkflow'](arg1, arg2, arg3, arg4);
}

export function ToggleTodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleTodo'](arg1, arg2, arg3);
}

export function TransitionIssueStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransitionIssueStatus'](arg1, arg2, arg3);
}

export function UnarchiveProject(arg1, arg2) {
  return window['go']['main']['App']['UnarchiveProject'](arg1, arg2);
}

export function UpdateIssueBody(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIssueBody'](arg1, arg2, arg3);
}

export function WriteDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteDocument'](arg1, arg2, arg3);
}
