// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIssueLink(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddIssueLink'](arg1, arg2, arg3, arg4);
}

export function AddProjectMember(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddProjectMember'](arg1, arg2, arg3, arg4);
}

export function AddTimelineNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTimelineNote'](arg1, arg2, arg3);
}

export function CreateIssue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateIssue'](arg1, arg2, arg3, arg4);
}

export function GetIdentity(arg1) {
  return window['go']['main']['App']['GetIdentity'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReadDocument(arg1, arg2) {
  return window['go']['main']['App']['ReadDocument'](arg1, arg2);
}

export function SelectWorkspaceFolder() {
  return window['go']['main']['App']['SelectWorkspaceFolder']();
}

export function SetIdentity(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIdentity'](arg1, arg2, arg3);
}

export function SetIssueAssignee(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIssueAssignee'](arg1, arg2, arg3);
}

export function SetIssueParent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIssueParent'](arg1, arg2, arg3);
}

export function SetIssueTitle(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIssueTitle'](arg1, arg2, arg3);
}

export function TransitionIssueStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransitionIssueStatus'](arg1, arg2, arg3);
}

export function UpdateIssueBody(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIssueBody'](arg1, arg2, arg3);
}

export function WriteDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteDocument'](arg1, arg2, arg3);
}
