// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';

export function AddIssueLink(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.Issue>;

export function AddProfile(arg1:string,arg2:string):Promise<workspace.Profile>;

export function AddProjectMember(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.Project>;

export function AddProjectRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.Project>;

export function AddTimelineNote(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function AddUser(arg1:string,arg2:string,arg3:string):Promise<workspace.User>;

export function ArchiveProject(arg1:string,arg2:string):Promise<workspace.Project>;

export function CloneProjectRepos(arg1:string,arg2:string):Promise<workspace.CloneResult>;

export function CreateIssue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.Issue>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<workspace.Project>;

export function DeleteDocument(arg1:string,arg2:string):Promise<void>;

export function DeleteIssue(arg1:string,arg2:string):Promise<void>;

export function GetIdentity(arg1:string):Promise<workspace.Identity>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitPull(arg1:string):Promise<void>;

export function GitPush(arg1:string):Promise<void>;

export function GitStageAll(arg1:string):Promise<void>;

export function GitStagePaths(arg1:string,arg2:Array<string>):Promise<void>;

export function GitStatus(arg1:string):Promise<workspace.GitStatus>;

export function ListProfiles():Promise<Array<workspace.Profile>>;

export function OpenWorkspace(arg1:string):Promise<workspace.Workspace>;

export function ReadDocument(arg1:string,arg2:string):Promise<string>;

export function RecentWorkspaces():Promise<Array<workspace.RecentWorkspace>>;

export function RecordRecentWorkspace(arg1:string):Promise<void>;

export function RemoveProfile(arg1:string):Promise<void>;

export function RemoveProjectRepo(arg1:string,arg2:string,arg3:string):Promise<workspace.Project>;

export function RemoveUser(arg1:string,arg2:string):Promise<void>;

export function SelectWorkspaceFolder(arg1:string):Promise<string>;

export function SetActiveProfile(arg1:string,arg2:string):Promise<void>;

export function SetIdentity(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetIssueAssignee(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function SetIssueParent(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function SetIssuePriority(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function SetIssueTitle(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function SetProjectIssueTypes(arg1:string,arg2:string,arg3:Array<string>):Promise<workspace.Project>;

export function SetUserLinks(arg1:string,arg2:string,arg3:string,arg4:string):Promise<workspace.User>;

export function SetWorkflow(arg1:string,arg2:string,arg3:Array<workspace.Status>,arg4:Array<workspace.Transition>):Promise<workspace.Project>;

export function ToggleTodo(arg1:string,arg2:string,arg3:number):Promise<workspace.Issue>;

export function TransitionIssueStatus(arg1:string,arg2:string,arg3:string):Promise<workspace.Issue>;

export function UnarchiveProject(arg1:string,arg2:string):Promise<workspace.Project>;

export function UpdateIssueBody(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteDocument(arg1:string,arg2:string,arg3:string):Promise<void>;
